### PR TITLE
Fix bug import

### LINKED ISSUE #82: Change code logic to check if the monthly stock URL is accessible before deleting database
See https://github.com/betagouv/sirene_as_api/issues/81

### PR DESCRIPTION
**Pull request by Samuelfaure**
- Fixed #82
- Also updated some packages because of new security vulnerability

In production this sunday.

### CODE REVIEW

File: app/interactors/get_last_monthly_stock_link.rb [hunk 1]
```diff
@@ -4,52 +4,61 @@
...
   around do |interactor|
     stdout_info_log 'Visiting monthly stock distant directory'
+    fail_server_unavailable unless available?(files_domain)
+
     interactor.call
-    stdout_success_log "Retrieved last monthly stock link : #{context.link}"
+
+    stdout_success_log "Retrieved last monthly stock link name : #{context.link}"
+    fail_link_unavailable unless available?(context.link)
     puts
```
Comment (Samuelfaure) [inline app/interactors/get_last_monthly_stock_link.rb]: @giglemap I didnt dare to remove the puts here, can you remind me what it was for ?
